version: 2.1
#jobs:
#  build:
#    docker:
#      - image: circleci/ruby:2.4.1
#    steps:
#      - checkout
#      - run:  echo "A first hello"
#     
# version: 2.1
#
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/ruby:2.3.0
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/ruby:2.3.0
    steps:
      - checkout
      - run: echo "this is the test job"
